server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1065036510
#    1065036510
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D://pillar/,file:D://bookBarcode
  mvc:
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xkx.bookmanager.pojo
  configuration:
    map-underscore-to-camel-case: true
